export {
  syncClaudeUpdateButtonUI,
  checkClaudeCodeUpdate,
  refreshClaudeUpdatePopoverIfOpen,
  renderSettingsUpdateSectionIfOpen,
  runClaudeCodeSilentUpdate,
  renderClaudeUpdatePopoverBody,
  bindClaudeUpdatePopoverEvents,
  closeClaudeUpdatePopover,
  shouldShowClaudeUpdateBadge,
  getClaudeUpdateButtonTitle,
  renderClaudeUpdateIcon,
} from './claude-update';
export {
  shouldShowAppUpdateBadge,
  shouldShowSettingsUpdateBadge,
  syncSettingsUpdateBadgeUI,
  getAppUpdateButtonTitle,
  renderAppUpdateIcon,
  syncAppUpdateButtonUI,
  initAppUpdate,
  checkAppUpdate,
  renderAppUpdateNotes,
  renderAppUpdateProgressHtml,
  renderAppUpdatePopoverBody,
  bindAppUpdatePopoverEvents,
  closeAppUpdatePopover,
  relaunchAfterUpdate,
  installAppUpdate,
} from './app-update';
